name: Sync Fork

on:
  schedule:
    - cron: '0 9 * * *' # every day 09:00
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: pcyan
          base: master
          head: master
